docs: added idf strings to docstrings of to_idf() functions
ladybug-tools/honeybee-energy pull request #1050
Opened 2024-11-15 01:07 UTC by TfedUD

@chriswmackey I triple checked I didn't miss any but could be wrong

2024-11-15 19:48 UTC, chriswmackey reviewed
Thanks @TfedUD .

This is a big help. I just have one comment about one of the docstrings that is so long that it's a bit unreadable. Once we change that, we should be able to merge.

2024-11-15 19:48 UTC, chriswmackey commented on honeybee_energy/simulation/parameter.py
> +
Having all of these output vairables here is making the IDF string a little unread-able. What if you just use this code to make the object before you run to_idf:

```
sim_par = SimulationParameter()
sim_par .output.add_output('Zone Ideal Loads Supply Air Total Heating Energy')
sim_par .output.add_output('Zone Ideal Loads Supply Air Total Cooling Energy')
print(sim_par.to_idf()
```

2024-11-15 19:57 UTC, chriswmackey requested changes
Actually, I take it back. It looks like generating the Sphinx docs with all of these new docstrings is giving a bunch of warnings:

![image](https://github.com/user-attachments/assets/6fcab070-79df-4ca8-b0b6-2456a0e2897d)

It looks like a lot of this has to do with improper indentation. I see that this PR also added a bunch of blank lines lines that contain whitespace, which is not following PEP8:

![image](https://github.com/user-attachments/assets/abe70eb8-b755-4955-af5d-774157c827ee)

You should look at how it is done with the to_dict methods for a sample of how to format these, @TfedUD . Once we can generate the sphinx docs without these warnings and we take out the black whitespaces, we'll be in good shape.

2024-11-15 19:59 UTC, chriswmackey commented
Note: the first warning above from Sphinx is my fault. If you fix it, it will be appreciated but just fixing all of the warnings related to to_idf() methods is good enough to merge.

2024-11-15 21:48 UTC, TfedUD commented
Hi @chriswmackey sorry about the issues! I'll start working on getting them fixed!

2024-11-16 15:38 UTC, TfedUD commented
@chriswmackey  for reference, the last one has the whitespace?
![whitespace](https://github.com/user-attachments/assets/85d34522-54fe-4471-8a92-5862e25d94bb)

2024-11-18 18:49 UTC, merged